rails_dependencies:
  image: busybox
  volumes:
    - /vendored_gems
    - /db
node_dependencies:
  image: busybox
  volumes:
    - /app/node_modules
app:
  build: .
  volumes_from:
    - rails_dependencies
    - node_dependencies
  ports:
    - '0.0.0.0:3000:3000'
  volumes:
    - '.:/app'
